
object vehicle_weapon_plasmabeam : vehicle_weapon_streamshot {
	void				UpdateStreamEffect();
}

void vehicle_weapon_plasmabeam::UpdateStreamEffect() {
	
	if ( !streamEffectHandle ) {
		streamEffectHandle = vehicle.playJointEffectViewSuppress( "fx_plasmabeam_fire", jointHandle, 1, 0 );
	}

	if( sys.getTime() > nextFiringSound ) {
		nextFiringSound = sys.getTime() + vehicle.startSound( "snd_flamethrower_stream", SND_WEAPON_FIRE );
	}
}