
object vehicle_weapon_plasmabeam : vehicle_weapon_streamshot {
	void				UpdateStreamEffect( vector endOrigin );
}

void vehicle_weapon_plasmabeam::UpdateStreamEffect( vector endOrigin ) {
	
	if ( !streamEffectHandle ) {
		streamEffectHandle = vehicle.playClippedJointEffect( "fx_plasmabeam_fire", jointHandle, 1, endOrigin );
	}

	if( sys.getTime() > nextFiringSound ) {
		nextFiringSound = sys.getTime() + vehicle.startSound( "snd_flamethrower_stream", SND_WEAPON_FIRE );
	}
}