
#include <quickchat/common.include>

// Global ///////////////////////////////////////////////////

quickChatDef gdf/quickchat/global/yes {
	_chat( "gdf/quickchat/global/yes", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/no {
	_chat( "gdf/quickchat/global/no", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/thanks {
	_chat( "gdf/quickchat/global/thanks", "", "global", BOT_TYPE_THANKS, "" )
}

quickChatDef gdf/quickchat/global/youwelcome {
	_chat( "gdf/quickchat/global/youwelcome", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/sorry {
	_chat( "gdf/quickchat/global/sorry", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/hi {
	_chat( "gdf/quickchat/global/hi", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/bye {
	_chat( "gdf/quickchat/global/bye", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/quiet {
	_chat( "gdf/quickchat/global/quiet", "", "global", BOT_TYPE_NONE, "" )
}


// Global Cheers ////////////////////////////////////////////

quickChatDef gdf/quickchat/global/cheers/awesome {
	_chat( "gdf/quickchat/global/cheers/awesome", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/cheers/greatshot {
	_chat( "gdf/quickchat/global/cheers/greatshot", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/cheers/freedomofearth {
	_chat( "gdf/quickchat/global/cheers/freedomofearth", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/cheers/wellplayed {
	_chat( "gdf/quickchat/global/cheers/wellplayed", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/cheers/goodgame {
	_chat( "gdf/quickchat/global/cheers/goodgame", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/cheers/gdf {
	_chat( "gdf/quickchat/global/cheers/gdf", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/cheers/yourock {
	_chat( "gdf/quickchat/global/cheers/yourock", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/cheers/alright {
	_chat( "gdf/quickchat/global/cheers/alright", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/cheers/bullseye {
	_chat( "gdf/quickchat/global/cheers/bullseye", "", "global", BOT_TYPE_NONE, "" )
}


// Global Taunts ////////////////////////////////////////////

quickChatDef gdf/quickchat/global/taunts/ohdear {
   	_chat( "gdf/quickchat/global/taunts/ohdear", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/oops {
	_chat( "gdf/quickchat/global/taunts/oops", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/enemyweakened {
	_chat( "gdf/quickchat/global/taunts/enemyweakened", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/theyrunningaway {
	_chat( "gdf/quickchat/global/taunts/theyrunningaway", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/eatthatstrogg {
	_chat( "gdf/quickchat/global/taunts/eatthatstrogg", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/killalienscum {
	_chat( "gdf/quickchat/global/taunts/killalienscum", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/denied {
	_chat( "gdf/quickchat/global/taunts/denied", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/grr {
	_chat( "gdf/quickchat/global/taunts/grr", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/cough {
	_chat( "gdf/quickchat/global/taunts/cough", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/awkward {
	_chat( "gdf/quickchat/global/taunts/awkward", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/awyeahohno {
	_chat( "gdf/quickchat/global/taunts/awyeahohno", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/awnoheyyeah {
	_chat( "gdf/quickchat/global/taunts/awnoheyyeah", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/owned {
	_chat( "gdf/quickchat/global/taunts/owned", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/thathurt {
	_chat( "gdf/quickchat/global/taunts/thathurt", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/thathadtohurt {
	_chat( "gdf/quickchat/global/taunts/thathadtohurt", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/meh {
	_chat( "gdf/quickchat/global/taunts/meh", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/global/taunts/ihadworse {
	_chat( "gdf/quickchat/global/taunts/ihadworse", "", "global", BOT_TYPE_NONE, "" )
}


// Responses ////////////////////////////////////////////////

quickChatDef gdf/quickchat/responses/acknowledged {
	_chat( "gdf/quickchat/responses/acknowledged", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/responses/declined {
	_chat( "gdf/quickchat/responses/declined", "", "team", BOT_TYPE_CMD_DECLINED, "" )
}

quickChatDef gdf/quickchat/responses/onit {
	_chat( "gdf/quickchat/responses/onit", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/responses/onmyway {
	_chat( "gdf/quickchat/responses/onmyway", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/responses/sorry {
	_chat( "gdf/quickchat/responses/sorry", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/responses/dontcare {
	_chat( "gdf/quickchat/responses/dontcare", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/responses/unabletoassist {
	_chat( "gdf/quickchat/responses/unabletoassist", "", "team", BOT_TYPE_CMD_DECLINED, "" )
}

quickChatDef gdf/quickchat/responses/outofrange {
	_chat( "gdf/quickchat/responses/outofrange", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/responses/thanks {
	_chat( "gdf/quickchat/responses/thanks", "", "team", BOT_TYPE_THANKS, "" )
}

quickChatDef gdf/quickchat/responses/youwelcome {
	_chat( "gdf/quickchat/responses/youwelcome", "", "team", BOT_TYPE_NONE, "" )
}


// Needs ////////////////////////////////////////////////////

quickChatDef gdf/quickchat/need/medic {
	_chat( "gdf/quickchat/need/medic", "RequestMedic", "team", BOT_TYPE_HEAL_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/need/ammo {
	_chat( "gdf/quickchat/need/ammo", "RequestAmmo", "team", BOT_TYPE_REARM_ME, "( ability_giveAmmo || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/need/engineer {
	_chat( "gdf/quickchat/need/engineer", "", "team", BOT_TYPE_NONE, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/need/backup {
	_chat( "gdf/quickchat/need/backup", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef gdf/quickchat/need/coveringfire {
	_chat( "gdf/quickchat/need/coveringfire", "QC_FlashCMIconFriend", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef gdf/quickchat/need/firesupport {
	_chat( "gdf/quickchat/need/firesupport", "", "team", BOT_TYPE_NONE, "( ability_fieldops || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/need/mines {
	_chat( "gdf/quickchat/need/mines", "", "team", BOT_TYPE_NONE, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/need/supplystation {
	_chat( "gdf/quickchat/need/supplystation", "", "team", BOT_TYPE_NONE, "( ability_revive || ( same_entity == true ) ) && same_team" )
}



// Team Needs ///////////////////////////////////////////////

quickChatDef gdf/quickchat/need/team/medic {
	_chat( "gdf/quickchat/need/team/medic", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/fieldops {
	_chat( "gdf/quickchat/need/team/fieldops", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/engineer {
	_chat( "gdf/quickchat/need/team/engineer", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/covertops {
	_chat( "gdf/quickchat/need/team/covertops", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/soldier {
	_chat( "gdf/quickchat/need/team/soldier", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/radar {
	_chat( "gdf/quickchat/need/team/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/apt {
	_chat( "gdf/quickchat/need/team/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/avt {
	_chat( "gdf/quickchat/need/team/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/ait {
	_chat( "gdf/quickchat/need/team/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/need/team/snipersupport {
	_chat( "gdf/quickchat/need/team/snipersupport", "", "team", BOT_TYPE_NONE, "" )
}


// Vehicles /////////////////////////////////////////////////

quickChatDef gdf/quickchat/vehicles/needvehicle {
	_chat( "gdf/quickchat/vehicles/needvehicle", "RequestHusky", "team", BOT_TYPE_NONE, "same_entity" )
	avdbit	1
}

quickChatDef gdf/quickchat/vehicles/needgunner {
	_chat( "gdf/quickchat/vehicles/needgunner", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef gdf/quickchat/vehicles/needdriver {
	_chat( "gdf/quickchat/vehicles/needdriver", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef gdf/quickchat/vehicles/needpilot {
	_chat( "gdf/quickchat/vehicles/needpilot", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef gdf/quickchat/vehicles/needrepairs {
	_chat( "gdf/quickchat/vehicles/needrepairs", "", "team", BOT_TYPE_NEED_REPAIR, "" )
}

quickChatDef gdf/quickchat/vehicles/needpickup {
	_chat( "gdf/quickchat/vehicles/needpickup", "RequestPickup", "team", BOT_TYPE_CONTEXT_NEED_RIDE, "" )
}

quickChatDef gdf/quickchat/vehicles/vehicleready {
	_chat( "gdf/quickchat/vehicles/vehicleready", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/vehicles/holdvehicle {
	_chat( "gdf/quickchat/vehicles/holdvehicle", "", "team", BOT_TYPE_CONTEXT_NEED_RIDE, "" )
}

quickChatDef gdf/quickchat/vehicles/bailout {
	_chat( "gdf/quickchat/vehicles/bailout", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/vehicles/needpassenger {
	_chat( "gdf/quickchat/vehicles/needpassenger", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

// Enemy ////////////////////////////////////////////////////

quickChatDef gdf/quickchat/enemy/infantryspotted {
	_chat( "gdf/quickchat/enemy/infantryspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/indisguise {
	_chat( "gdf/quickchat/enemy/indisguise", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/vehiclespotted {
	_chat( "gdf/quickchat/enemy/vehiclespotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/armorspotted {
	_chat( "gdf/quickchat/enemy/armorspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/aircraftspotted {
	_chat( "gdf/quickchat/enemy/aircraftspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/infiltratorspotted {
	_chat( "gdf/quickchat/enemy/infiltratorspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/minesspotted {
	_chat( "gdf/quickchat/enemy/minesspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/incomingairstrike {
	_chat( "gdf/quickchat/enemy/incomingairstrike", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/incomingbombardment {
	_chat( "gdf/quickchat/enemy/incomingbombardment", "", "team", BOT_TYPE_NONE, "" )
}


// Enemy Deployables ////////////////////////////////////////

quickChatDef gdf/quickchat/enemy/deployables/aitspotted {
	_chat( "gdf/quickchat/enemy/deployables/aitspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/deployables/firesupportspotted {
	_chat( "gdf/quickchat/enemy/deployables/firesupportspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/deployables/aptspotted {
	_chat( "gdf/quickchat/enemy/deployables/aptspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/deployables/avtspotted {
	_chat( "gdf/quickchat/enemy/deployables/avtspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/enemy/deployables/radarspotted {
	_chat( "gdf/quickchat/enemy/deployables/radarspotted", "", "team", BOT_TYPE_NONE, "" )
}


// Commands /////////////////////////////////////////////////

quickChatDef gdf/quickchat/commands/move {
	_chat( "gdf/quickchat/commands/move", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/commands/letsgo {
	_chat( "gdf/quickchat/commands/letsgo", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/commands/followme {
	_chat( "gdf/quickchat/commands/followme", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef gdf/quickchat/commands/clearmines {
	_chat( "gdf/quickchat/commands/clearmines", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/commands/hackenemybase {
	_chat( "gdf/quickchat/commands/hackenemybase", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/commands/captureforwardspawn {
	_chat( "gdf/quickchat/commands/captureforwardspawn", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/commands/constructguardtower {
	_chat( "gdf/quickchat/commands/constructguardtower", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/commands/holdfire {
	_chat( "gdf/quickchat/commands/holdfire", "", "team", BOT_TYPE_NONE, "" )
}


// Objectives ///////////////////////////////////////////////

quickChatDef gdf/quickchat/objectives/attack {
	_chat( "gdf/quickchat/objectives/attack", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/defend {
	_chat( "gdf/quickchat/objectives/defend", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/destroy {
	_chat( "gdf/quickchat/objectives/destroy", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/hack {
	_chat( "gdf/quickchat/objectives/hack", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/construct {
	_chat( "gdf/quickchat/objectives/construct", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/construct_tower {
	_chat( "gdf/quickchat/objectives/construct_tower", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/destroy_tower {
	_chat( "gdf/quickchat/objectives/destroy_tower", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/take {
	_chat( "gdf/quickchat/objectives/take", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/return {
	_chat( "gdf/quickchat/objectives/return", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/disarmexplosives {
	_chat( "gdf/quickchat/objectives/disarmexplosives", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/escortmcp {
	_chat( "gdf/quickchat/objectives/escortmcp", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/objectives/repairmcp {
	_chat( "gdf/quickchat/objectives/repairmcp", "", "team", BOT_TYPE_NONE, "" )
}


// Self /////////////////////////////////////////////////////

quickChatDef gdf/quickchat/self/imsoldier {
	_chat( "gdf/quickchat/self/imsoldier", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/immedic {
	_chat( "gdf/quickchat/self/immedic", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/imengineer {
	_chat( "gdf/quickchat/self/imengineer", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/imcovertops {
	_chat( "gdf/quickchat/self/imcovertops", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/imfieldops {
	_chat( "gdf/quickchat/self/imfieldops", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/imattacking {
	_chat( "gdf/quickchat/self/imattacking", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/imdefending {
	_chat( "gdf/quickchat/self/imdefending", "", "team", BOT_TYPE_NONE, "" )
}


// Self Disguise ////////////////////////////////////////////

quickChatDef gdf/quickchat/self/disguise/imindisguise {
	_chat( "gdf/quickchat/self/disguise/imindisguise", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/disguise/enemydisguisedasme {
	_chat( "gdf/quickchat/self/disguise/enemydisguisedasme", "", "team", BOT_TYPE_ENEMY_DISGUISED_AS_ME, "" )
}


// Self Deploying////////////////////////////////////////////

quickChatDef gdf/quickchat/self/deploying/radar {
	_chat( "gdf/quickchat/self/deploying/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deploying/apt {
	_chat( "gdf/quickchat/self/deploying/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deploying/avt {
	_chat( "gdf/quickchat/self/deploying/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deploying/ait {
	_chat( "gdf/quickchat/self/deploying/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deploying/artillery {
	_chat( "gdf/quickchat/self/deploying/artillery", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deploying/rockets {
	_chat( "gdf/quickchat/self/deploying/rockets", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deploying/hammer {
	_chat( "gdf/quickchat/self/deploying/hammer", "", "team", BOT_TYPE_NONE, "" )
}


// Self Deployed /////////////////////////////////////////////

quickChatDef gdf/quickchat/self/deployed/radar {
	_chat( "gdf/quickchat/self/deployed/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deployed/apt {
	_chat( "gdf/quickchat/self/deployed/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deployed/avt {
	_chat( "gdf/quickchat/self/deployed/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deployed/ait {
	_chat( "gdf/quickchat/self/deployed/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deployed/artillery {
	_chat( "gdf/quickchat/self/deployed/artillery", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deployed/rockets {
	_chat( "gdf/quickchat/self/deployed/rockets", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/deployed/hammer {
	_chat( "gdf/quickchat/self/deployed/hammer", "", "team", BOT_TYPE_NONE, "" )
}


// Self Items ///////////////////////////////////////////////

quickChatDef gdf/quickchat/self/items/plantingmines {
	_chat( "gdf/quickchat/self/items/plantingmines", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/items/disarmingmines {
	_chat( "gdf/quickchat/self/items/disarmingmines", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/items/suppliesdropped {
	_chat( "gdf/quickchat/self/items/suppliesdropped", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/items/healthpacksdropped {
	_chat( "gdf/quickchat/self/items/healthpacksdropped", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/items/medpacksdropped {
	_chat( "gdf/quickchat/self/items/medpacksdropped", "ContextHealthDropped", "team", BOT_TYPE_NONE, "( ( ability_revive == false ) || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/self/items/ammopacksdropped {
	_chat( "gdf/quickchat/self/items/ammopacksdropped", "ContextAmmoDropped", "team", BOT_TYPE_NONE, "( ( ability_giveAmmo == false ) || ( same_entity == true ) ) && same_team" )
}


// Self Repairing ///////////////////////////////////////////

quickChatDef gdf/quickchat/self/repairing/radar {
	_chat( "gdf/quickchat/self/repairing/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repairing/apt {
	_chat( "gdf/quickchat/self/repairing/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repairing/avt {
	_chat( "gdf/quickchat/self/repairing/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repairing/ait {
	_chat( "gdf/quickchat/self/repairing/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repairing/artillery {
	_chat( "gdf/quickchat/self/repairing/artillery", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repairing/rockets {
	_chat( "gdf/quickchat/self/repairing/rockets", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repairing/hammer {
	_chat( "gdf/quickchat/self/repairing/hammer", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repairing/mcp {
	_chat( "gdf/quickchat/self/repairing/mcp", "", "team", BOT_TYPE_NONE, "" )
}


// Self Repairing ///////////////////////////////////////////

quickChatDef gdf/quickchat/self/repaired/radar {
	_chat( "gdf/quickchat/self/repaired/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repaired/apt {
	_chat( "gdf/quickchat/self/repaired/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repaired/avt {
	_chat( "gdf/quickchat/self/repaired/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repaired/ait {
	_chat( "gdf/quickchat/self/repaired/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repaired/artillery {
	_chat( "gdf/quickchat/self/repaired/artillery", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repaired/rockets {
	_chat( "gdf/quickchat/self/repaired/rockets", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/self/repaired/hammer {
	_chat( "gdf/quickchat/self/repaired/hammer", "", "team", BOT_TYPE_NONE, "" )
}


// Context Commands ///////////////////////////////////////////

quickChatDef gdf/quickchat/context/hack {
	_chat( "gdf/quickchat/objectives/hack", "ContextHack", "team", BOT_TYPE_CONTEXT_DO_OBJECTIVE, "" )
}

quickChatDef gdf/quickchat/context/construct {
	_chat( "gdf/quickchat/objectives/construct", "ContextConstruct", "team", BOT_TYPE_CONTEXT_DO_OBJECTIVE, "" )
}

quickChatDef gdf/quickchat/context/construct_tower {
	_chat( "gdf/quickchat/objectives/construct_tower", "ContextConstruct", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/context/repair/mg_nest {
	_chat( "gdf/quickchat/context/repair/mg_nest", "ContextConstruct", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/context/destroy {
	_chat( "gdf/quickchat/objectives/destroy", "ContextDestroy", "team", BOT_TYPE_CONTEXT_DO_OBJECTIVE, "" )
}

quickChatDef gdf/quickchat/context/disarmexplosives {
	_chat( "gdf/quickchat/objectives/disarmexplosives", "ContextDisarm", "team", BOT_TYPE_CONTEXT_DO_OBJECTIVE, "" )
}

quickChatDef gdf/quickchat/context/spawnhost {
	_chat( "gdf/quickchat/need/medic", "ContextSpawnHost", "team", BOT_TYPE_NONE, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/spawnhost_destroy {
	_chat( "gdf/quickchat/context/spawnhost_destroy", "ContextDestroy", "team", BOT_TYPE_NONE, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/revive {
	_chat( "gdf/quickchat/need/medic", "RequestRevive", "team", BOT_TYPE_REVIVE_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/health {
	_chat( "gdf/quickchat/need/medic", "RequestMedic", "team", BOT_TYPE_HEAL_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/health_other {
	_chat( "gdf/quickchat/need/medic", "ContextHeal", "team", BOT_TYPE_HEAL_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/ammo {
	_chat( "gdf/quickchat/need/ammo", "RequestAmmo", "team", BOT_TYPE_REARM_ME, "( ability_giveAmmo || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/ammo_other {
	_chat( "gdf/quickchat/need/ammo", "ContextAmmo", "team", BOT_TYPE_REARM_ME, "( ability_giveAmmo || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/repair/vehicle {
	_chat( "gdf/quickchat/context/repair/vehicle", "ContextRepairMyVehicle", "team", BOT_TYPE_CONTEXT_REPAIR_TARGET, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/repair/vehicle_other {
	_chat( "gdf/quickchat/context/repair/vehicle_other", "ContextRepairThing", "team", BOT_TYPE_CONTEXT_REPAIR_TARGET, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/repair/deployable_other {
	_chat( "gdf/quickchat/context/repair/deployable_other", "ContextRepairThing", "team", BOT_TYPE_CONTEXT_REPAIR_TARGET, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef gdf/quickchat/context/attack/enemy {
	_chat( "gdf/quickchat/enemy/infantryspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/deployable {
	_chat( "gdf/quickchat/enemy/armorspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/vehicle {
	_chat( "gdf/quickchat/enemy/vehiclespotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/pickup {
	_chat( "gdf/quickchat/vehicles/needpickup", "ContextPickup", "team", BOT_TYPE_CONTEXT_NEED_RIDE, "same_entity || other_in_vehicle == true" )
}

quickChatDef gdf/quickchat/context/needdriver {
	_chat( "gdf/quickchat/vehicles/needdriver", "RequestPassenger", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef gdf/quickchat/context/needgunner {
	_chat( "gdf/quickchat/vehicles/needgunner", "RequestPassenger", "team", BOT_TYPE_NEED_ESCORT, "same_entity || other_in_vehicle == false" )
}

quickChatDef gdf/quickchat/context/needpassenger {
	_chat( "gdf/quickchat/vehicles/needpassenger", "RequestPassenger", "team", BOT_TYPE_NEED_ESCORT, "same_entity || other_in_vehicle == false" )
}

quickChatDef gdf/quickchat/context/waypoints {
	_chat( "gdf/quickchat/context/waypoints", "ContextWaypoint", "fireteam", BOT_TYPE_NONE, "same_fireteam" )
}

quickChatDef gdf/quickchat/context/attack/aitspotted {
	_chat( "gdf/quickchat/enemy/deployables/aitspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/firesupportspotted {
	_chat( "gdf/quickchat/enemy/deployables/firesupportspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/aptspotted {
	_chat( "gdf/quickchat/enemy/deployables/aptspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/avtspotted {
	_chat( "gdf/quickchat/enemy/deployables/avtspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/radarspotted {
	_chat( "gdf/quickchat/enemy/deployables/radarspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/vehiclespotted {
	_chat( "gdf/quickchat/enemy/vehiclespotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/armorspotted {
	_chat( "gdf/quickchat/enemy/armorspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/attack/aircraftspotted {
	_chat( "gdf/quickchat/enemy/aircraftspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef gdf/quickchat/context/defend {
	_chat( "gdf/quickchat/objectives/defend", "ContextDefend", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/context/escortmcp {
	_chat( "gdf/quickchat/objectives/escortmcp", "ContextDefend", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/context/repairmcp {
	_chat( "gdf/quickchat/objectives/repairmcp", "ContextDefend", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/context/defendforwardspawn {
	_chat( "gdf/quickchat/context/defendforwardspawn", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/context/liberateforwardspawn {
	_chat( "gdf/quickchat/context/liberateforwardspawn", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef gdf/quickchat/context/followme {
	_chat( "gdf/quickchat/context/followme", "ContextFollowMe", "team", BOT_TYPE_NONE, "" )
}

// Fireteam  ///////////////////////////////////////////

quickChatDef gdf/quickchat/fireteam/waypoint/attack {
	_chat( "gdf/quickchat/fireteam/waypoint/attack", "", "fireteam", BOT_TYPE_NONE, "same_fireteam" )
}

quickChatDef gdf/quickchat/fireteam/waypoint/defend {
	_chat( "gdf/quickchat/fireteam/waypoint/defend", "", "fireteam", BOT_TYPE_NONE, "same_fireteam" )
}

quickChatDef gdf/quickchat/fireteam/waypoint/regroup {
	_chat( "gdf/quickchat/fireteam/waypoint/regroup", "ContextWaypoint", "fireteam", BOT_TYPE_NONE, "same_fireteam" )
}
