
#include <quickchat/common.include>

// Global ///////////////////////////////////////////////////

quickChatDef strogg/quickchat/global/yes {
	_chat( "strogg/quickchat/global/yes", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/no {
	_chat( "strogg/quickchat/global/no", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/thanks {
	_chat( "strogg/quickchat/global/thanks", "", "global", BOT_TYPE_THANKS, "" )
}

quickChatDef strogg/quickchat/global/youwelcome {
	_chat( "strogg/quickchat/global/youwelcome", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/sorry {
	_chat( "strogg/quickchat/global/sorry", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/hi {
	_chat( "strogg/quickchat/global/hi", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/go {
	_chat( "strogg/quickchat/global/go", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/quiet {
	_chat( "strogg/quickchat/global/quiet", "", "global", BOT_TYPE_NONE, "" )
}


// Global Cheers ////////////////////////////////////////////

quickChatDef strogg/quickchat/global/cheers/awesome {
	_chat( "strogg/quickchat/global/cheers/awesome", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/cheers/greatshot {
	_chat( "strogg/quickchat/global/cheers/greatshot", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/cheers/forthemakron {
	_chat( "strogg/quickchat/global/cheers/forthemakron", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/cheers/wellplayed {
	_chat( "strogg/quickchat/global/cheers/wellplayed", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/cheers/goodgame {
	_chat( "strogg/quickchat/global/cheers/goodgame", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/cheers/strogg {
	_chat( "strogg/quickchat/global/cheers/strogg", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/cheers/yourock {
	_chat( "strogg/quickchat/global/cheers/yourock", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/cheers/alright {
	_chat( "strogg/quickchat/global/cheers/alright", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/cheers/accurate {
	_chat( "strogg/quickchat/global/cheers/accurate", "", "global", BOT_TYPE_NONE, "" )
}


// Global Taunts ////////////////////////////////////////////

quickChatDef strogg/quickchat/global/taunts/ohdear {
	_chat( "strogg/quickchat/global/taunts/ohdear", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/oops {
	_chat( "strogg/quickchat/global/taunts/oops", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/theycrumble {
	_chat( "strogg/quickchat/global/taunts/theycrumble", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/theyfleeterror {
	_chat( "strogg/quickchat/global/taunts/theyfleeterror", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/eatthathuman {
	_chat( "strogg/quickchat/global/taunts/eatthathuman", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/killhumanfood {
	_chat( "strogg/quickchat/global/taunts/killhumanfood", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/thwarted {
	_chat( "strogg/quickchat/global/taunts/thwarted", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/rrr {
	_chat( "strogg/quickchat/global/taunts/rrr", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/cough {
	_chat( "strogg/quickchat/global/taunts/cough", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/awkward {
	_chat( "strogg/quickchat/global/taunts/awkward", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/awyeahohno {
	_chat( "strogg/quickchat/global/taunts/awyeahohno", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/awnoheyyeah {
	_chat( "strogg/quickchat/global/taunts/awnoheyyeah", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/owned {
	_chat( "strogg/quickchat/global/taunts/owned", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/thathurt {
	_chat( "strogg/quickchat/global/taunts/thathurt", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/thathadtohurt {
	_chat( "strogg/quickchat/global/taunts/thathadtohurt", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/meh {
	_chat( "strogg/quickchat/global/taunts/meh", "", "global", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/global/taunts/ihadworse {
	_chat( "strogg/quickchat/global/taunts/ihadworse", "", "global", BOT_TYPE_NONE, "" )
}


// Responses ////////////////////////////////////////////////

quickChatDef strogg/quickchat/responses/acknowledged {
	_chat( "strogg/quickchat/responses/acknowledged", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/responses/declined {
	_chat( "strogg/quickchat/responses/declined", "", "team", BOT_TYPE_CMD_DECLINED, "" )
}

quickChatDef strogg/quickchat/responses/onit {
	_chat( "strogg/quickchat/responses/onit", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/responses/onmyway {
	_chat( "strogg/quickchat/responses/onmyway", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/responses/sorry {
	_chat( "strogg/quickchat/responses/sorry", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/responses/dontcare {
	_chat( "strogg/quickchat/responses/dontcare", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/responses/unabletoassist {
	_chat( "strogg/quickchat/responses/unabletoassist", "", "team", BOT_TYPE_CMD_DECLINED, "" )
}

quickChatDef strogg/quickchat/responses/outofrange {
	_chat( "strogg/quickchat/responses/outofrange", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/responses/thanks {
	_chat( "strogg/quickchat/responses/thanks", "", "team", BOT_TYPE_THANKS, "" )
}

quickChatDef strogg/quickchat/responses/youwelcome {
	_chat( "strogg/quickchat/responses/youwelcome", "", "team", BOT_TYPE_NONE, "" )
}


// Needs ////////////////////////////////////////////////////

quickChatDef strogg/quickchat/need/technician {
	_chat( "strogg/quickchat/need/technician", "RequestMedic", "team", BOT_TYPE_HEAL_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/need/stroyent {
	_chat( "strogg/quickchat/need/stroyent", "RequestMedic", "team", BOT_TYPE_REARM_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/need/constructor {
	_chat( "strogg/quickchat/need/constructor", "", "team", BOT_TYPE_NONE, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/need/backup {
	_chat( "strogg/quickchat/need/backup", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef strogg/quickchat/need/coveringfire {
	_chat( "strogg/quickchat/need/coveringfire", "QC_FlashCMIconFriend", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef strogg/quickchat/need/firesupport {
	_chat( "strogg/quickchat/need/firesupport", "", "team", BOT_TYPE_NONE, "( ability_oppressor || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/need/mines {
	_chat( "strogg/quickchat/need/mines", "", "team", BOT_TYPE_NONE, "( ability_repair || ( same_entity == true ) ) && same_team" )
}


// Team Needs ///////////////////////////////////////////////

quickChatDef strogg/quickchat/need/team/technician {
	_chat( "strogg/quickchat/need/team/technician", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/oppressor {
	_chat( "strogg/quickchat/need/team/oppressor", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/constructor {
	_chat( "strogg/quickchat/need/team/constructor", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/infiltrator {
	_chat( "strogg/quickchat/need/team/infiltrator", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/aggressor {
	_chat( "strogg/quickchat/need/team/aggressor", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/radar {
	_chat( "strogg/quickchat/need/team/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/apt {
	_chat( "strogg/quickchat/need/team/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/avt {
	_chat( "strogg/quickchat/need/team/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/ait {
	_chat( "strogg/quickchat/need/team/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/need/team/snipersupport {
	_chat( "strogg/quickchat/need/team/snipersupport", "", "team", BOT_TYPE_NONE, "" )
}


// Vehicles /////////////////////////////////////////////////

quickChatDef strogg/quickchat/vehicles/needvehicle {
	_chat( "strogg/quickchat/vehicles/needvehicle", "RequestIcarus", "team", BOT_TYPE_NONE, "same_entity" )
	avdbit	128
}

quickChatDef strogg/quickchat/vehicles/needgunner {
	_chat( "strogg/quickchat/vehicles/needgunner", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef strogg/quickchat/vehicles/needdriver {
	_chat( "strogg/quickchat/vehicles/needdriver", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef strogg/quickchat/vehicles/needpilot {
	_chat( "strogg/quickchat/vehicles/needpilot", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef strogg/quickchat/vehicles/needrepairs {
	_chat( "strogg/quickchat/vehicles/needrepairs", "", "team", BOT_TYPE_NEED_REPAIR, "" )
}

quickChatDef strogg/quickchat/vehicles/needpickup {
	_chat( "strogg/quickchat/vehicles/needpickup", "RequestPickup", "team", BOT_TYPE_CONTEXT_NEED_RIDE, "" )
}

quickChatDef strogg/quickchat/vehicles/vehicleready {
	_chat( "strogg/quickchat/vehicles/vehicleready", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/vehicles/holdvehicle {
	_chat( "strogg/quickchat/vehicles/holdvehicle", "", "team", BOT_TYPE_CONTEXT_NEED_RIDE, "" )
}

quickChatDef strogg/quickchat/vehicles/bailout {
	_chat( "strogg/quickchat/vehicles/bailout", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/vehicles/needpassenger {
	_chat( "strogg/quickchat/vehicles/needpassenger", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

// Enemy ////////////////////////////////////////////////////

quickChatDef strogg/quickchat/enemy/infantryspotted {
	_chat( "strogg/quickchat/enemy/infantryspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/indisguise {
	_chat( "strogg/quickchat/enemy/indisguise", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/vehiclespotted {
	_chat( "strogg/quickchat/enemy/vehiclespotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/armorspotted {
	_chat( "strogg/quickchat/enemy/armorspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/aircraftspotted {
	_chat( "strogg/quickchat/enemy/aircraftspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/covertopsspotted {
	_chat( "strogg/quickchat/enemy/covertopsspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/minesspotted {
	_chat( "strogg/quickchat/enemy/minesspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/incomingairstrike {
	_chat( "strogg/quickchat/enemy/incomingairstrike", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/incomingbombardment {
	_chat( "strogg/quickchat/enemy/incomingbombardment", "", "team", BOT_TYPE_NONE, "" )
}


// Enemy Deployables ////////////////////////////////////////

quickChatDef strogg/quickchat/enemy/deployables/aitspotted {
	_chat( "strogg/quickchat/enemy/deployables/aitspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/deployables/firesupportspotted {
	_chat( "strogg/quickchat/enemy/deployables/firesupportspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/deployables/aptspotted {
	_chat( "strogg/quickchat/enemy/deployables/aptspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/deployables/avtspotted {
	_chat( "strogg/quickchat/enemy/deployables/avtspotted", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/enemy/deployables/radarspotted {
	_chat( "strogg/quickchat/enemy/deployables/radarspotted", "", "team", BOT_TYPE_NONE, "" )
}


// Commands /////////////////////////////////////////////////

quickChatDef strogg/quickchat/commands/move {
	_chat( "strogg/quickchat/commands/move", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/commands/letsgo {
	_chat( "strogg/quickchat/commands/letsgo", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/commands/followme {
	_chat( "strogg/quickchat/commands/followme", "", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef strogg/quickchat/commands/clearmines {
	_chat( "strogg/quickchat/commands/clearmines", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/commands/hackenemybase {
	_chat( "strogg/quickchat/commands/hackenemybase", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/commands/captureforwardspawn {
	_chat( "strogg/quickchat/commands/captureforwardspawn", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/commands/holdfire {
	_chat( "strogg/quickchat/commands/holdfire", "", "team", BOT_TYPE_NONE, "" )
}


// Objectives ///////////////////////////////////////////////

quickChatDef strogg/quickchat/objectives/attack {
	_chat( "strogg/quickchat/objectives/attack", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/defend {
	_chat( "strogg/quickchat/objectives/defend", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/destroy {
	_chat( "strogg/quickchat/objectives/destroy", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/destroy_tower {
	_chat( "strogg/quickchat/objectives/destroy_tower", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/hack {
	_chat( "strogg/quickchat/objectives/hack", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/construct {
	_chat( "strogg/quickchat/objectives/construct", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/construct_tower {
	_chat( "strogg/quickchat/objectives/construct", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/take {
	_chat( "strogg/quickchat/objectives/take", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/return {
	_chat( "strogg/quickchat/objectives/return", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/disarmexplosives {
	_chat( "strogg/quickchat/objectives/disarmexplosives", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/stopmcp {
	_chat( "strogg/quickchat/objectives/stopmcp", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/objectives/disablemcp {
	_chat( "strogg/quickchat/objectives/disablemcp", "", "team", BOT_TYPE_NONE, "" )
}


// Self /////////////////////////////////////////////////////

quickChatDef strogg/quickchat/self/imaggressor {
	_chat( "strogg/quickchat/self/imaggressor", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/imtechnician {
	_chat( "strogg/quickchat/self/imtechnician", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/imconstructor {
	_chat( "strogg/quickchat/self/imconstructor", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/imoppressor {
	_chat( "strogg/quickchat/self/imoppressor", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/iminfiltrator {
	_chat( "strogg/quickchat/self/iminfiltrator", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/imattacking {
	_chat( "strogg/quickchat/self/imattacking", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/imdefending {
	_chat( "strogg/quickchat/self/imdefending", "", "team", BOT_TYPE_NONE, "" )
}


// Self Disguise ////////////////////////////////////////////

quickChatDef strogg/quickchat/self/disguise/imindisguise {
	_chat( "strogg/quickchat/self/disguise/imindisguise", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/disguise/enemydisguisedasme {
	_chat( "strogg/quickchat/self/disguise/enemydisguisedasme", "", "team", BOT_TYPE_ENEMY_DISGUISED_AS_ME, "" )
}


// Self Deploying////////////////////////////////////////////

quickChatDef strogg/quickchat/self/deploying/radar {
	_chat( "strogg/quickchat/self/deploying/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deploying/apt {
	_chat( "strogg/quickchat/self/deploying/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deploying/avt {
	_chat( "strogg/quickchat/self/deploying/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deploying/ait{
	_chat( "strogg/quickchat/self/deploying/ait", "", "team", BOT_TYPE_NONE, "" )
} 

quickChatDef strogg/quickchat/self/deploying/railhowitzer {
	_chat( "strogg/quickchat/self/deploying/railhowitzer", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deploying/plasmamortar {
	_chat( "strogg/quickchat/self/deploying/plasmamortar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deploying/dmc {
	_chat( "strogg/quickchat/self/deploying/dmc", "", "team", BOT_TYPE_NONE, "" )
}


// Self Deployed /////////////////////////////////////////////

quickChatDef strogg/quickchat/self/deployed/radar {
	_chat( "strogg/quickchat/self/deployed/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deployed/apt {
	_chat( "strogg/quickchat/self/deployed/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deployed/avt {
	_chat( "strogg/quickchat/self/deployed/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deployed/ait {
	_chat( "strogg/quickchat/self/deployed/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deployed/railhowitzer {
	_chat( "strogg/quickchat/self/deployed/railhowitzer", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deployed/plasmamortar {
	_chat( "strogg/quickchat/self/deployed/plasmamortar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/deployed/dmc {
	_chat( "strogg/quickchat/self/deployed/dmc", "", "team", BOT_TYPE_NONE, "" )
}


// Self Items ///////////////////////////////////////////////

quickChatDef strogg/quickchat/self/items/plantingmines {
	_chat( "strogg/quickchat/self/items/plantingmines", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/items/disarmingmines {
	_chat( "strogg/quickchat/self/items/disarmingmines", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/items/spawnhostcreated {
	_chat( "strogg/quickchat/self/items/spawnhostcreated", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/items/stroyentdropped {
	_chat( "strogg/quickchat/self/items/stroyentdropped", "ContextStroyentDropped", "team", BOT_TYPE_NONE, "( ( ability_revive == false ) || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/self/items/shielddeployed {
	_chat( "strogg/quickchat/self/items/shielddeployed", "", "team", BOT_TYPE_NONE, "" )
}


// Self Repairing ///////////////////////////////////////////

quickChatDef strogg/quickchat/self/repairing/radar {
	_chat( "strogg/quickchat/self/repairing/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repairing/apt {
	_chat( "strogg/quickchat/self/repairing/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repairing/avt {
	_chat( "strogg/quickchat/self/repairing/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repairing/ait {
	_chat( "strogg/quickchat/self/repairing/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repairing/railhowitzer {
	_chat( "strogg/quickchat/self/repairing/railhowitzer", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repairing/plasmamortar {
	_chat( "strogg/quickchat/self/repairing/plasmamortar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repairing/dmc {
	_chat( "strogg/quickchat/self/repairing/dmc", "", "team", BOT_TYPE_NONE, "" )
}


// Self Repairing ///////////////////////////////////////////

quickChatDef strogg/quickchat/self/repaired/radar {
	_chat( "strogg/quickchat/self/repaired/radar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repaired/apt {
	_chat( "strogg/quickchat/self/repaired/apt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repaired/avt {
	_chat( "strogg/quickchat/self/repaired/avt", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repaired/ait {
	_chat( "strogg/quickchat/self/repaired/ait", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repaired/railhowitzer {
	_chat( "strogg/quickchat/self/repaired/railhowitzer", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repaired/plasmamortar {
	_chat( "strogg/quickchat/self/repaired/plasmamortar", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/self/repaired/dmc {
	_chat( "strogg/quickchat/self/repaired/dmc", "", "team", BOT_TYPE_NONE, "" )
}

// Context Commands ///////////////////////////////////////////

quickChatDef strogg/quickchat/context/hack {
	_chat( "strogg/quickchat/objectives/hack", "ContextHack", "team", BOT_TYPE_CONTEXT_DO_OBJECTIVE, "" )
}

quickChatDef strogg/quickchat/context/construct {
	_chat( "strogg/quickchat/objectives/construct", "ContextConstruct", "team", BOT_TYPE_CONTEXT_DO_OBJECTIVE, "" )
}

quickChatDef strogg/quickchat/context/destroy {
	_chat( "strogg/quickchat/objectives/destroy", "ContextDestroy", "team", BOT_TYPE_CONTEXT_DO_OBJECTIVE, "" )
}

quickChatDef strogg/quickchat/context/destroy_tower {
	_chat( "strogg/quickchat/objectives/destroy_tower", "ContextDestroy", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/context/destroy/mg_nest {
	_chat( "strogg/quickchat/context/destroy/mg_nest", "ContextDestroy", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/context/disarmexplosives {
	_chat( "strogg/quickchat/objectives/disarmexplosives", "ContextDisarm", "team", BOT_TYPE_CONTEXT_DO_OBJECTIVE, "" )
}

quickChatDef strogg/quickchat/context/spawnhost {
	_chat( "strogg/quickchat/context/spawnhost", "ContextSpawnHost", "team", BOT_TYPE_NONE, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/context/revive {
	_chat( "strogg/quickchat/need/technician", "RequestRevive", "team", BOT_TYPE_REVIVE_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/context/stroyent {
	_chat( "strogg/quickchat/need/stroyent", "RequestMedic", "team", BOT_TYPE_REARM_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/context/stroyent_other {
	_chat( "strogg/quickchat/need/technician", "ContextHeal", "team", BOT_TYPE_HEAL_ME, "( ability_revive || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/context/repair/vehicle {
	_chat( "strogg/quickchat/context/repair/vehicle", "ContextRepairMyVehicle", "team", BOT_TYPE_CONTEXT_REPAIR_TARGET, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/context/repair/vehicle_other {
	_chat( "strogg/quickchat/context/repair/vehicle_other", "ContextRepairThing", "team", BOT_TYPE_CONTEXT_REPAIR_TARGET, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/context/repair/deployable_other {
	_chat( "strogg/quickchat/context/repair/deployable_other", "ContextRepairThing", "team", BOT_TYPE_CONTEXT_REPAIR_TARGET, "( ability_repair || ( same_entity == true ) ) && same_team" )
}

quickChatDef strogg/quickchat/context/attack/enemy {
	_chat( "strogg/quickchat/enemy/infantryspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/deployable {
	_chat( "strogg/quickchat/enemy/armorspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/vehicle {
	_chat( "strogg/quickchat/enemy/vehiclespotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/pickup {
	_chat( "strogg/quickchat/vehicles/needpickup", "ContextPickup", "team", BOT_TYPE_CONTEXT_NEED_RIDE, "same_entity || other_in_vehicle == true" )
}

quickChatDef strogg/quickchat/context/needdriver {
	_chat( "strogg/quickchat/vehicles/needdriver", "RequestPassenger", "team", BOT_TYPE_NEED_ESCORT, "" )
}

quickChatDef strogg/quickchat/context/needgunner {
	_chat( "strogg/quickchat/vehicles/needgunner", "RequestPassenger", "team", BOT_TYPE_NEED_ESCORT, "same_entity || other_in_vehicle == false" )
}

quickChatDef strogg/quickchat/context/needpassenger {
	_chat( "strogg/quickchat/vehicles/needpassenger", "RequestPassenger", "team", BOT_TYPE_NEED_ESCORT, "same_entity || other_in_vehicle == false" )
}

quickChatDef strogg/quickchat/context/waypoints {
	_chat( "strogg/quickchat/context/waypoints", "ContextWaypoint", "fireteam", BOT_TYPE_NONE, "same_fireteam" )
}

quickChatDef strogg/quickchat/context/attack/aitspotted {
	_chat( "strogg/quickchat/enemy/deployables/aitspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/firesupportspotted {
	_chat( "strogg/quickchat/enemy/deployables/firesupportspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/aptspotted {
	_chat( "strogg/quickchat/enemy/deployables/aptspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/avtspotted {
	_chat( "strogg/quickchat/enemy/deployables/avtspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/radarspotted {
	_chat( "strogg/quickchat/enemy/deployables/radarspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/vehiclespotted {
	_chat( "strogg/quickchat/enemy/vehiclespotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/armorspotted {
	_chat( "strogg/quickchat/enemy/armorspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/attack/aircraftspotted {
	_chat( "strogg/quickchat/enemy/aircraftspotted", "ContextKill", "team", BOT_TYPE_CONTEXT_KILL_TARGET, "" )
}

quickChatDef strogg/quickchat/context/defend {
	_chat( "strogg/quickchat/objectives/defend", "ContextDefend", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/context/stopmcp {
	_chat( "strogg/quickchat/objectives/stopmcp", "ContextDestroy", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/context/hack_gates {
	_chat( "strogg/quickchat/context/hack_gates", "ContextHack", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/context/defendforwardspawn {
	_chat( "strogg/quickchat/context/defendforwardspawn", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/context/liberateforwardspawn {
	_chat( "strogg/quickchat/context/liberateforwardspawn", "", "team", BOT_TYPE_NONE, "" )
}

quickChatDef strogg/quickchat/context/followme {
	_chat( "strogg/quickchat/context/followme", "ContextFollowMe", "team", BOT_TYPE_NONE, "" )
}

// Fireteam  ///////////////////////////////////////////

quickChatDef strogg/quickchat/fireteam/waypoint/attack {
	_chat( "strogg/quickchat/fireteam/waypoint/attack", "", "fireteam", BOT_TYPE_NONE, "same_fireteam" )
}

quickChatDef strogg/quickchat/fireteam/waypoint/defend {
	_chat( "strogg/quickchat/fireteam/waypoint/defend", "", "fireteam", BOT_TYPE_NONE, "same_fireteam" )
}

quickChatDef strogg/quickchat/fireteam/waypoint/regroup {
	_chat( "strogg/quickchat/fireteam/waypoint/regroup", "ContextWaypoint", "fireteam", BOT_TYPE_NONE, "same_fireteam" )
}
